apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: m6n7fx22u-python 
  janus-idp.io/tekton: m6n7fx22u-python
  backstage.io/kubernetes-id: m6n7fx22u-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: m6n7fx22u-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml